version: '3.8'

name: resume-system
services:
  resume-backend:
    image: resume-backend
    ports:
      - "8000:8000"
    depends_on:
      - resume-db
      - resume-redis
    volumes:
      - ./backend/.env:/app/.env
      - ./backend/uploads:/app/uploads
    environment:
      - REDIS_HOST=resume-redis
      - REDIS_PORT=6379
      - REDIS_DB=0

  resume-celery-worker:
    image: resume-celery-worker 
    command: celery -A app.services.resume_queue_service worker --loglevel=info
    depends_on:
      - resume-db
      - resume-redis
    volumes:
      - ./backend/.env:/app/.env
      - ./backend/uploads:/app/uploads
    environment:
      - REDIS_HOST=resume-redis
      - REDIS_PORT=6379
      - REDIS_DB=0

  resume-celery-beat:
    image: resume-celery-beat
    command: celery -A app.services.resume_queue_service beat --loglevel=info
    depends_on:
      - resume-db
      - resume-redis
    volumes:
      - ./backend/.env:/app/.env
      - ./backend/uploads:/app/uploads
    environment:
      - REDIS_HOST=resume-redis
      - REDIS_PORT=6379
      - REDIS_DB=0

  resume-celery-flower:
    image: resume-celery-worker
    command: celery -A app.services.resume_queue_service flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - resume-celery-worker
      - resume-redis
    volumes:
      - ./backend/.env:/app/.env
    environment:
      - REDIS_HOST=resume-redis
      - REDIS_PORT=6379
      - REDIS_DB=0

  resume-frontend:
    image: resume-frontend
    ports:
      - "6110:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - resume-backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  resume-db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo
    ports:
      - "5420:5432"
    volumes:
      - resume_postgres_data-prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  resume-redis:
    image: redis:7
    ports:
      - "6380:6379"
    volumes:
      - resume_redis_data-prod:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  resume_postgres_data-prod:
  resume_redis_data-prod:
