"""Add QYWX fields

Revision ID: 90c13c4c5224
Revises: 
Create Date: 2025-04-23 17:32:40.266577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '90c13c4c5224'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('certifications', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('active', 'inactive', name='certification_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index('idx_certification_status', table_name='certifications')
    op.drop_index('idx_certification_tenant', table_name='certifications')
    op.create_index(op.f('ix_certifications_id'), 'certifications', ['id'], unique=False)
    op.create_unique_constraint('uk_tenant_certification', 'certifications', ['tenant_id', 'name'])
    op.create_index(op.f('ix_job_required_certifications_id'), 'job_required_certifications', ['id'], unique=False)
    op.drop_column('job_required_certifications', 'created_at')
    op.drop_column('job_required_certifications', 'updated_at')
    op.create_index(op.f('ix_job_required_skills_id'), 'job_required_skills', ['id'], unique=False)
    op.drop_column('job_required_skills', 'created_at')
    op.drop_column('job_required_skills', 'updated_at')
    op.alter_column('jobs', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('jobs', 'department',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='所属部门',
               existing_nullable=True)
    op.alter_column('jobs', 'headcount',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('jobs', 'salary_min',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('jobs', 'salary_max',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('jobs', 'salary_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('日薪', '月薪', '年薪', '面议', name='salary_type'),
               comment=None,
               existing_comment='薪资类型：日薪、月薪、年薪或面议',
               existing_nullable=False)
    op.alter_column('jobs', 'salary_structure',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='薪资构成说明，如基本工资、绩效奖金等',
               existing_nullable=True)
    op.alter_column('jobs', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('jobs', 'preferences',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='加分项说明，非必需的优先考虑条件',
               existing_nullable=True)
    op.alter_column('jobs', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('draft', 'published', 'closed', name='job_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.drop_index('idx_jobs_department', table_name='jobs')
    op.drop_index('idx_jobs_job_type', table_name='jobs')
    op.drop_index('idx_jobs_location', table_name='jobs')
    op.drop_index('idx_jobs_publisher', table_name='jobs')
    op.drop_index('idx_jobs_salary_type', table_name='jobs')
    op.drop_index('idx_jobs_status', table_name='jobs')
    op.drop_index('idx_jobs_tenant', table_name='jobs')
    op.drop_constraint('jobs_external_id_key', 'jobs', type_='unique')
    op.create_index(op.f('ix_jobs_external_id'), 'jobs', ['external_id'], unique=True)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.drop_column('jobs', 'updated_at')
    op.alter_column('llm_configs', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('llm_configs', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('llm_configs', 'chat_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('llm_configs', 'chat_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('llm_configs', 'embedding_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_llm_configs_name', table_name='llm_configs')
    op.create_index(op.f('ix_llm_configs_id'), 'llm_configs', ['id'], unique=False)
    op.create_index(op.f('ix_llm_configs_name'), 'llm_configs', ['name'], unique=False)
    op.drop_index('idx_notifications_tenant', table_name='notifications')
    op.drop_index('idx_notifications_user', table_name='notifications')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.drop_index('idx_permission_name', table_name='permission')
    op.create_index(op.f('ix_permission_id'), 'permission', ['id'], unique=False)
    op.alter_column('resume_repositories', 'resume_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='简历类型，默认为general',
               existing_nullable=False,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('resume_repositories', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='租户ID',
               existing_nullable=False)
    op.alter_column('resume_repositories', 'processing_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='处理状态',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('resume_repositories', 'processing_started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('resume_repositories', 'processing_completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint('idx_resume_repositories_name_tenant', 'resume_repositories', type_='unique')
    op.drop_index('idx_resume_repositories_status', table_name='resume_repositories')
    op.drop_index('idx_resume_repositories_tenant', table_name='resume_repositories')
    op.drop_index('idx_resume_repositories_type', table_name='resume_repositories')
    op.create_index(op.f('ix_resume_repositories_id'), 'resume_repositories', ['id'], unique=False)
    op.create_index(op.f('ix_resume_repositories_name'), 'resume_repositories', ['name'], unique=False)
    op.create_index(op.f('ix_resume_repositories_tenant_id'), 'resume_repositories', ['tenant_id'], unique=False)
    op.drop_table_comment(
        'resume_repositories',
        existing_comment='简历库表',
        schema=None
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_permission_id'), 'role_permission', ['id'], unique=False)
    op.alter_column('skills', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('active', 'inactive', name='skill_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index('idx_skill_status', table_name='skills')
    op.drop_index('idx_skill_tenant', table_name='skills')
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_unique_constraint('uk_tenant_skill', 'skills', ['tenant_id', 'name'])
    op.alter_column('talent', 'gender',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('M', 'F', name='gender_type'),
               existing_nullable=True)
    op.alter_column('talent', 'data_source',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('个人用户', '技术学校', '人力公司', '租户自建', name='data_source_type'),
               existing_nullable=True,
               existing_server_default=sa.text("'个人用户'::character varying"))
    op.drop_index('idx_talent_email', table_name='talent')
    op.drop_index('idx_talent_phone', table_name='talent')
    op.drop_index('idx_talent_tenant', table_name='talent')
    op.create_index(op.f('ix_talent_talent_id'), 'talent', ['talent_id'], unique=False)
    op.add_column('talent_certification', sa.Column('certification_type_id', sa.Integer(), nullable=False))
    op.drop_index('idx_certification_talent', table_name='talent_certification')
    op.create_index(op.f('ix_talent_certification_certification_id'), 'talent_certification', ['certification_id'], unique=False)
    op.create_foreign_key(None, 'talent_certification', 'certifications', ['certification_type_id'], ['id'])
    op.drop_index('idx_education_talent', table_name='talent_education')
    op.create_index(op.f('ix_talent_education_education_id'), 'talent_education', ['education_id'], unique=False)
    op.drop_index('idx_experience_talent', table_name='talent_experience')
    op.create_index(op.f('ix_talent_experience_experience_id'), 'talent_experience', ['experience_id'], unique=False)
    op.alter_column('talent_pool', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('talent_pool', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_talent_pool_tenant', table_name='talent_pool')
    op.create_index(op.f('ix_talent_pool_pool_id'), 'talent_pool', ['pool_id'], unique=False)
    op.alter_column('talent_pool_member', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_pool_member_pool', table_name='talent_pool_member')
    op.drop_index('idx_pool_member_talent', table_name='talent_pool_member')
    op.create_index(op.f('ix_talent_pool_member_member_id'), 'talent_pool_member', ['member_id'], unique=False)
    op.drop_index('idx_talent_skill_skill', table_name='talent_skill')
    op.drop_index('idx_talent_skill_talent', table_name='talent_skill')
    op.create_index(op.f('ix_talent_skill_talent_skill_id'), 'talent_skill', ['talent_skill_id'], unique=False)
    op.add_column('tenant', sa.Column('qywx_corp_id', sa.String(length=100), nullable=True, comment='企业微信CorpID'))
    op.add_column('tenant', sa.Column('qywx_permanent_code', sa.String(length=512), nullable=True, comment='企业微信永久授权码'))
    op.add_column('tenant', sa.Column('qywx_agent_id', sa.Integer(), nullable=True, comment='企业微信应用AgentID'))
    op.add_column('tenant', sa.Column('auth_user_id', sa.String(length=100), nullable=True, comment='授权管理员UserId'))
    op.add_column('tenant', sa.Column('auth_time', sa.DateTime(), nullable=True, comment='授权时间'))
    op.add_column('tenant', sa.Column('expiry_time', sa.DateTime(), nullable=True, comment='授权过期时间'))
    op.add_column('tenant', sa.Column('subscription_type', sa.String(length=50), nullable=True, comment='订阅类型: trial, basic, premium'))
    op.add_column('tenant', sa.Column('subscription_start', sa.DateTime(), nullable=True, comment='订阅开始时间'))
    op.add_column('tenant', sa.Column('subscription_end', sa.DateTime(), nullable=True, comment='订阅结束时间'))
    op.alter_column('tenant', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('active', 'inactive', name='tenant_status'),
               existing_nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.create_index(op.f('ix_tenant_id'), 'tenant', ['id'], unique=False)
    op.alter_column('trial_applications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='申请用户ID（可选）')
    op.alter_column('trial_applications', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='公司名称',
               existing_nullable=False)
    op.alter_column('trial_applications', 'contact_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='联系人姓名',
               existing_nullable=False)
    op.alter_column('trial_applications', 'contact_phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='联系电话',
               existing_nullable=False)
    op.alter_column('trial_applications', 'contact_email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='联系邮箱',
               existing_nullable=False)
    op.alter_column('trial_applications', 'company_size',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='公司规模',
               existing_nullable=True)
    op.alter_column('trial_applications', 'business_description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='业务描述',
               existing_nullable=True)
    op.alter_column('trial_applications', 'application_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='申请原因',
               existing_nullable=True)
    op.alter_column('trial_applications', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='申请状态(pending:待审核,active:试用中,rejected:已拒绝,expired:已过期)',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('trial_applications', 'reject_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='拒绝原因',
               existing_nullable=True)
    op.alter_column('trial_applications', 'trial_start_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='试用开始时间',
               existing_nullable=True)
    op.alter_column('trial_applications', 'trial_end_date',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='试用结束时间',
               existing_nullable=True)
    op.drop_index('idx_trial_applications_dates', table_name='trial_applications')
    op.drop_index('idx_trial_applications_status', table_name='trial_applications')
    op.drop_index('idx_trial_applications_user', table_name='trial_applications')
    op.create_index(op.f('ix_trial_applications_id'), 'trial_applications', ['id'], unique=False)
    op.drop_table_comment(
        'trial_applications',
        existing_comment='试用申请表',
        schema=None
    )
    op.create_index(op.f('ix_user_role_id'), 'user_role', ['id'], unique=False)
    op.add_column('users', sa.Column('qywx_userid', sa.String(length=100), nullable=True, comment='企业微信用户ID'))
    op.add_column('users', sa.Column('qywx_avatar', sa.String(length=255), nullable=True, comment='企业微信头像URL'))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'user_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('candidate', 'tenant', 'admin', name='user_type'),
               nullable=False,
               existing_server_default=sa.text("'tenant'::character varying"))
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_phone', table_name='users')
    op.drop_index('idx_users_tenant', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_tenant', 'users', ['tenant_id'], unique=False)
    op.create_index('idx_users_phone', 'users', ['phone'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.alter_column('users', 'user_type',
               existing_type=sa.Enum('candidate', 'tenant', 'admin', name='user_type'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'tenant'::character varying"))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'qywx_avatar')
    op.drop_column('users', 'qywx_userid')
    op.drop_index(op.f('ix_user_role_id'), table_name='user_role')
    op.create_table_comment(
        'trial_applications',
        '试用申请表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_trial_applications_id'), table_name='trial_applications')
    op.create_index('idx_trial_applications_user', 'trial_applications', ['user_id'], unique=False)
    op.create_index('idx_trial_applications_status', 'trial_applications', ['status'], unique=False)
    op.create_index('idx_trial_applications_dates', 'trial_applications', ['trial_start_date', 'trial_end_date'], unique=False)
    op.alter_column('trial_applications', 'trial_end_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='试用结束时间',
               existing_nullable=True)
    op.alter_column('trial_applications', 'trial_start_date',
               existing_type=postgresql.TIMESTAMP(),
               comment='试用开始时间',
               existing_nullable=True)
    op.alter_column('trial_applications', 'reject_reason',
               existing_type=sa.TEXT(),
               comment='拒绝原因',
               existing_nullable=True)
    op.alter_column('trial_applications', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='申请状态(pending:待审核,active:试用中,rejected:已拒绝,expired:已过期)',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('trial_applications', 'application_reason',
               existing_type=sa.TEXT(),
               comment='申请原因',
               existing_nullable=True)
    op.alter_column('trial_applications', 'business_description',
               existing_type=sa.TEXT(),
               comment='业务描述',
               existing_nullable=True)
    op.alter_column('trial_applications', 'company_size',
               existing_type=sa.VARCHAR(length=50),
               comment='公司规模',
               existing_nullable=True)
    op.alter_column('trial_applications', 'contact_email',
               existing_type=sa.VARCHAR(length=255),
               comment='联系邮箱',
               existing_nullable=False)
    op.alter_column('trial_applications', 'contact_phone',
               existing_type=sa.VARCHAR(length=20),
               comment='联系电话',
               existing_nullable=False)
    op.alter_column('trial_applications', 'contact_name',
               existing_type=sa.VARCHAR(length=100),
               comment='联系人姓名',
               existing_nullable=False)
    op.alter_column('trial_applications', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment='公司名称',
               existing_nullable=False)
    op.alter_column('trial_applications', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='申请用户ID（可选）')
    op.drop_index(op.f('ix_tenant_id'), table_name='tenant')
    op.alter_column('tenant', 'status',
               existing_type=sa.Enum('active', 'inactive', name='tenant_status'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_column('tenant', 'subscription_end')
    op.drop_column('tenant', 'subscription_start')
    op.drop_column('tenant', 'subscription_type')
    op.drop_column('tenant', 'expiry_time')
    op.drop_column('tenant', 'auth_time')
    op.drop_column('tenant', 'auth_user_id')
    op.drop_column('tenant', 'qywx_agent_id')
    op.drop_column('tenant', 'qywx_permanent_code')
    op.drop_column('tenant', 'qywx_corp_id')
    op.drop_index(op.f('ix_talent_skill_talent_skill_id'), table_name='talent_skill')
    op.create_index('idx_talent_skill_talent', 'talent_skill', ['talent_id'], unique=False)
    op.create_index('idx_talent_skill_skill', 'talent_skill', ['skill_id'], unique=False)
    op.drop_index(op.f('ix_talent_pool_member_member_id'), table_name='talent_pool_member')
    op.create_index('idx_pool_member_talent', 'talent_pool_member', ['talent_id'], unique=False)
    op.create_index('idx_pool_member_pool', 'talent_pool_member', ['pool_id'], unique=False)
    op.alter_column('talent_pool_member', 'added_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_talent_pool_pool_id'), table_name='talent_pool')
    op.create_index('idx_talent_pool_tenant', 'talent_pool', ['tenant_id'], unique=False)
    op.alter_column('talent_pool', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('talent_pool', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_talent_experience_experience_id'), table_name='talent_experience')
    op.create_index('idx_experience_talent', 'talent_experience', ['talent_id'], unique=False)
    op.drop_index(op.f('ix_talent_education_education_id'), table_name='talent_education')
    op.create_index('idx_education_talent', 'talent_education', ['talent_id'], unique=False)
    op.drop_constraint(None, 'talent_certification', type_='foreignkey')
    op.drop_index(op.f('ix_talent_certification_certification_id'), table_name='talent_certification')
    op.create_index('idx_certification_talent', 'talent_certification', ['talent_id'], unique=False)
    op.drop_column('talent_certification', 'certification_type_id')
    op.drop_index(op.f('ix_talent_talent_id'), table_name='talent')
    op.create_index('idx_talent_tenant', 'talent', ['tenant_id'], unique=False)
    op.create_index('idx_talent_phone', 'talent', ['phone'], unique=False)
    op.create_index('idx_talent_email', 'talent', ['email'], unique=False)
    op.alter_column('talent', 'data_source',
               existing_type=sa.Enum('个人用户', '技术学校', '人力公司', '租户自建', name='data_source_type'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'个人用户'::character varying"))
    op.alter_column('talent', 'gender',
               existing_type=sa.Enum('M', 'F', name='gender_type'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_constraint('uk_tenant_skill', 'skills', type_='unique')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.create_index('idx_skill_tenant', 'skills', ['tenant_id'], unique=False)
    op.create_index('idx_skill_status', 'skills', ['status'], unique=False)
    op.alter_column('skills', 'status',
               existing_type=sa.Enum('active', 'inactive', name='skill_status'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index(op.f('ix_role_permission_id'), table_name='role_permission')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.create_table_comment(
        'resume_repositories',
        '简历库表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_resume_repositories_tenant_id'), table_name='resume_repositories')
    op.drop_index(op.f('ix_resume_repositories_name'), table_name='resume_repositories')
    op.drop_index(op.f('ix_resume_repositories_id'), table_name='resume_repositories')
    op.create_index('idx_resume_repositories_type', 'resume_repositories', ['resume_type'], unique=False)
    op.create_index('idx_resume_repositories_tenant', 'resume_repositories', ['tenant_id'], unique=False)
    op.create_index('idx_resume_repositories_status', 'resume_repositories', ['processing_status'], unique=False)
    op.create_unique_constraint('idx_resume_repositories_name_tenant', 'resume_repositories', ['name', 'tenant_id'])
    op.alter_column('resume_repositories', 'processing_completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('resume_repositories', 'processing_started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('resume_repositories', 'processing_status',
               existing_type=sa.VARCHAR(length=20),
               comment='处理状态',
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('resume_repositories', 'tenant_id',
               existing_type=sa.INTEGER(),
               comment='租户ID',
               existing_nullable=False)
    op.alter_column('resume_repositories', 'resume_type',
               existing_type=sa.VARCHAR(length=50),
               comment='简历类型，默认为general',
               existing_nullable=False,
               existing_server_default=sa.text("'general'::character varying"))
    op.drop_index(op.f('ix_permission_id'), table_name='permission')
    op.create_index('idx_permission_name', 'permission', ['name'], unique=False)
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.create_index('idx_notifications_user', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_notifications_tenant', 'notifications', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_llm_configs_name'), table_name='llm_configs')
    op.drop_index(op.f('ix_llm_configs_id'), table_name='llm_configs')
    op.create_index('idx_llm_configs_name', 'llm_configs', ['name'], unique=False)
    op.alter_column('llm_configs', 'embedding_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('llm_configs', 'chat_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('llm_configs', 'chat_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('llm_configs', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('llm_configs', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('jobs', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_external_id'), table_name='jobs')
    op.create_unique_constraint('jobs_external_id_key', 'jobs', ['external_id'])
    op.create_index('idx_jobs_tenant', 'jobs', ['tenant_id'], unique=False)
    op.create_index('idx_jobs_status', 'jobs', ['status'], unique=False)
    op.create_index('idx_jobs_salary_type', 'jobs', ['salary_type'], unique=False)
    op.create_index('idx_jobs_publisher', 'jobs', ['publisher_id'], unique=False)
    op.create_index('idx_jobs_location', 'jobs', ['location'], unique=False)
    op.create_index('idx_jobs_job_type', 'jobs', ['job_type'], unique=False)
    op.create_index('idx_jobs_department', 'jobs', ['department'], unique=False)
    op.alter_column('jobs', 'status',
               existing_type=sa.Enum('draft', 'published', 'closed', name='job_status'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('jobs', 'preferences',
               existing_type=sa.TEXT(),
               comment='加分项说明，非必需的优先考虑条件',
               existing_nullable=True)
    op.alter_column('jobs', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('jobs', 'salary_structure',
               existing_type=sa.TEXT(),
               comment='薪资构成说明，如基本工资、绩效奖金等',
               existing_nullable=True)
    op.alter_column('jobs', 'salary_type',
               existing_type=sa.Enum('日薪', '月薪', '年薪', '面议', name='salary_type'),
               type_=sa.VARCHAR(length=10),
               comment='薪资类型：日薪、月薪、年薪或面议',
               existing_nullable=False)
    op.alter_column('jobs', 'salary_max',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('jobs', 'salary_min',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('jobs', 'headcount',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('jobs', 'department',
               existing_type=sa.VARCHAR(length=100),
               comment='所属部门',
               existing_nullable=True)
    op.alter_column('jobs', 'title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('job_required_skills', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('job_required_skills', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_job_required_skills_id'), table_name='job_required_skills')
    op.add_column('job_required_certifications', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.add_column('job_required_certifications', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_job_required_certifications_id'), table_name='job_required_certifications')
    op.drop_constraint('uk_tenant_certification', 'certifications', type_='unique')
    op.drop_index(op.f('ix_certifications_id'), table_name='certifications')
    op.create_index('idx_certification_tenant', 'certifications', ['tenant_id'], unique=False)
    op.create_index('idx_certification_status', 'certifications', ['status'], unique=False)
    op.alter_column('certifications', 'status',
               existing_type=sa.Enum('active', 'inactive', name='certification_status'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    # ### end Alembic commands ### 